name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type to increment (major, minor, patch)'
        required: true
        default: 'patch'
      is_prerelease:
        type: boolean
        description: 'Set to true to create a pre release'
        required: true
        default: false

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine next version
        id: version
        run: |
          # Fetch tags from the remote
          git fetch --tags

          # Get the latest tag; if no tags, start from 0.0.0
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "Latest tag: $latest_tag"

          # Split the latest tag into major, minor, patch
          IFS='.' read -r major minor patch <<<"${latest_tag//[!0-9.]/}"

          # Increment based on the input release_type
          case "${{ github.event.inputs.release_type }}" in
            major) major=$((major + 1)); minor=0; patch=0 ;;
            minor) minor=$((minor + 1)); patch=0 ;;
            patch) patch=$((patch + 1)) ;;
            *) echo "Invalid release_type provided"; exit 1 ;;
          esac

          # Construct the new version tag
          new_version="${major}.${minor}.${patch}"
          echo "New version: $new_version"

          # Append "-alpha" if is_draft is true
          if [ "${{ github.event.inputs.is_prerelease }}" == "true" ]; then
            new_version="${new_version}-alpha"
          fi

          # Set the new version as an environment variable
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          # Use jq to update the version field in package.json
          jq '.version = env.new_version' package.json > temp.json && mv temp.json package.json

          # Commit and push the updated package.json
          git add package.json
          git commit -m "chore: update package.json version to $new_version"
          git push origin main

      - name: Create Tag
        run: |
          git tag -a "$new_version" -m "Release $new_version"
          git push origin "$new_version"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: '$new_version'
          release_name: 'Release $new_version'
          draft: false
          prerelease: ${{ github.event.inputs.is_prerelease }}
          body: 'Release for version $new_version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
